displayName: Simple Cache
summary: Simple cache plugin middleware caches responses on disk.
type: middleware
import: github.com/containous/plugin-simplecache
compatibility: TODO
testData:
  path: /tmp